### PR TITLE
minor typos in README.md

### PR DESCRIPTION
**Pull request by AvdN**

### CODE REVIEW

**Comment by Hejsil** [comment]
Thanks, but this change needs to be made in (`example/README.md.template`)[https://github.com/Hejsil/zig-clap/blob/master/example/README.md.template], because the `README.md` is generated from that during `zig build`

**Comment by AvdN** [comment]
It would be nice to have a comment at the top of both of the files as to that effect I think something like:
```
<!---
source for this file: example/README.md.template
-->
```
should work (but I probably would have missed that anyway ;-) )

**Comment by AvdN** [comment]
Are you going to change that, or do you want me to make a new pull-request?

**Comment by Hejsil** [comment]
Ops, I kinda forgot about this. I pushed the fix [here](https://github.com/Hejsil/zig-clap/commit/2d9da16aa3657d44cbc9b364c9e843d1c31408a8)

**Pull request closed without merging**
