### PR TITLE
12 compatible

### PR DESCRIPTION
**Pull request by jinzhongjia**
https://github.com/Hejsil/zig-clap/issues/128

### CODE REVIEW

**Comment by Hejsil** [comment]
Can I tag a version 0.9.1 with these changes, and then leave them out of master?

**Comment by jinzhongjia** [comment]
Of course, I think this is a better solution

**Comment by Hejsil** [comment]
Merged in [here](https://github.com/Hejsil/zig-clap/commit/d71cc39a94f3e6ccbad00c25d350c9147de4df9f) and created a release https://github.com/Hejsil/zig-clap/releases/tag/0.9.1

**Comment by jinzhongjia** [comment]
ok, thx

**Pull request closed without merging**
